# Generated by Django 5.0 on 2024-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgehistory',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10),
        ),
    ]
