# Generated by Django 5.0 on 2024-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_remove_fridgeitem_suplier_fridgeitem_auto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
