# Generated by Django 5.0 on 2024-02-06 11:22

import django.db.models.deletion
import fridge.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_alter_fridgeitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeitem',
            name='default_order_quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge.suplier'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_delivered', 'Order Delivered'), ('order_placed', 'New Order Placed'), ('item_expired', 'Item Expired'), ('item_removed', 'Item Removed'), ('item_inserted', 'Item Inserted'), ('fridge_opened', 'Fridge opened'), ('out_of_order', 'Out of Order')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=fridge.models.generate_rider_password, editable=False, max_length=12)),
                ('order_status', models.CharField(choices=[('processing', 'Processing'), ('delivered', 'Delivered')], default='processing', max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firdge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgeitem')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge.suplier')),
            ],
        ),
        migrations.DeleteModel(
            name='FridgeHistory',
        ),
    ]
