# Generated by Django 4.2.9 on 2024-02-07 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_fridgeitem_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
